use('bird-in-the-hand');
db.photo_library.deleteMany({});
db.photo_library.insertMany([
  {
    title: 'Blue-Black Grassquit',
    photo: 'assets/birds/blue-black-grassquit.jpg',
    votes: 120,
    uploadDate: new Date('2025-05-01'),
    author: 'John Bird',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Village Weaver',
    photo: 'assets/birds/village-weaver1.jpg',
    votes: 95,
    uploadDate: new Date('2025-05-03'),
    author: 'Jane Featherstone',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Lilac-Breasted Roller',
    photo: 'assets/birds/lilac-breasted-roller.jpg',
    votes: 150,
    uploadDate: new Date('2025-05-05'),
    author: 'Alice Nestington',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Better Village Weaver',
    photo: 'assets/birds/village-weaver2.jpg',
    votes: 200,
    uploadDate: new Date('2025-05-07'),
    author: 'Jane Featherstone',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Golden Pheasant',
    photo: 'assets/birds/lesser-spotted-eagle.jpg',
    votes: 180,
    uploadDate: new Date('2025-05-09'),
    author: 'Michael Beakman',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Toucan',
    photo: 'assets/birds/brown-hooded-kingfisher.jpg',
    votes: 170,
    uploadDate: new Date('2025-05-11'),
    author: 'Sarah Talon',
    comments: [],
    public: true,
    reports: 1
  },
  {
    title: 'Crested Barbet',
    photo: 'assets/birds/crested-barbet.jpg',
    votes: 190,
    uploadDate: new Date('2025-05-13'),
    author: 'Chris Flock',
    comments: [],
    public: true,
    reports: 0,
  },
  {
    title: 'Crested Barbet',
    photo: 'assets/birds/big-bird.jpg',
    votes: 190,
    uploadDate: new Date('2025-05-13'),
    author: 'Sarah Talon',
    comments: [],
    public: true,
    reports: 0,
  },
]);
